language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" 
    #  - "nightly" fails because of nose using depecrated function
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: nosetests
